//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_try3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.Manage = new HashSet<Manage>();
            this.Stores = new HashSet<Stores>();
        }
        [Key]
        [DisplayName("員工編號")]
        public int SN { get; set; }
        [DisplayName("使用者編號")]
        public int UserSN { get; set; }
        [DisplayName("姓名")]
        [Required]
        public string Name { get; set; }
        [DisplayName("職稱")]
        [Required]
        public string Title { get; set; }
        [DisplayName("電話")]
        [Required]
        public string Phone { get; set; }
        [DisplayName("分機")]
        public string Extension { get; set; }
        [DisplayName("信箱")]
        [Required]
        public string Email { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manage> Manage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stores> Stores { get; set; }
    }
}
