//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_try3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Members()
        {
            this.Comments = new HashSet<Comments>();
            this.GroupBuying = new HashSet<GroupBuying>();
            this.Manage = new HashSet<Manage>();
            this.Orders = new HashSet<Orders>();
            this.Stores = new HashSet<Stores>();
        }

        [Key]
        public int SN { get; set; }
        [DisplayName("帳號")]
        [Required(ErrorMessage = "欄位必填")]
        public int UserSN { get; set; }
        [DisplayName("姓名")]
        [Required(ErrorMessage = "欄位必填")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "字數最少2字，最多30字。")]

        public string Name { get; set; }
        [DisplayName("電話")]
        [Required(ErrorMessage = "欄位必填")]
        [StringLength(13, MinimumLength = 7, ErrorMessage = "字數最少7字，最多30字。")]


        public string Phone { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "欄位必填")]
        [StringLength(100, ErrorMessage = "字數最多100字。")]
        [DataType(DataType.Password)]
        public string Email { get; set; }

        [DisplayName("地址")]
        [Required(ErrorMessage = "欄位必填")]
        [StringLength(50, MinimumLength = 4, ErrorMessage = "字數最少14字，最多50字")]
        public string Address { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupBuying> GroupBuying { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manage> Manage { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stores> Stores { get; set; }
    }
}
