//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_try3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Orderdetails = new HashSet<Orderdetails>();
        }
    
        public string ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int PaySN { get; set; }
        public bool Payed { get; set; }
        public int CustomerSN { get; set; }
        public string GroupBuyingID { get; set; }
    
        public virtual GroupBuying GroupBuying { get; set; }
        public virtual Members Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderdetails> Orderdetails { get; set; }
        public virtual PayType PayType { get; set; }
    }
}
