//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_try3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Orderdetails = new HashSet<Orderdetails>();
        }

        [Key]
        [DisplayName("商品編號")]
        public int SN { get; set; }
        [DisplayName("品名")]
        [Required]
        [MaxLength(100, ErrorMessage = "字數上限為100字")]
        public string ProductName { get; set; }
        [DisplayName("庫存")]
        [Range(0, short.MaxValue, ErrorMessage = "庫存不可小於0")]
        [Required]
        public int Stock { get; set; }
        [DisplayName("單位")]
        [Required]
        [MaxLength(4, ErrorMessage = "字數上限為4字")]
        public string Unit { get; set; }
        [DisplayName("單價")]
        [Required]
        //[DisplayFormat(DataFormatString = "{0:C}", ApplyFormatInEditMode = false)]
        public decimal UnitPrice { get; set; }
        [DisplayName("已下架")]
        public Nullable<bool> Discontinued { get; set; }
        [DisplayName("商品照片")]
        public byte[] Photo { get; set; }
        [DisplayName("商品照片格式")]
        [MaxLength(10, ErrorMessage = "字數上限為10字")]
        public string PhotoType { get; set; }
        [DisplayName("建立日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        [DisplayName("種類")]
        public int CategorySN { get; set; }
        [DisplayName("商店")]
        public int StoreSN { get; set; }

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderdetails> Orderdetails { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
