//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_try3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Admin = new HashSet<Admin>();
            this.Members = new HashSet<Members>();
        }

        [Key]
        public int SN { get; set; }
        [DisplayName("帳號")]
        [StringLength(50, ErrorMessage = "字數最多50字")]
        [Required(ErrorMessage = "欄位必填")]

        public string Account { get; set; }

        string password = "";
        [DisplayName("密碼")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "欄位必填")]
        [MinLength(5, ErrorMessage = "請輸入5-16字")]
        [MaxLength(16, ErrorMessage = "請輸入5-16字")]

        public string Password
        {
            get { return password; }
            set { password = hashPw.getHashPwd(value); }
        }
        [DisplayName("加入時間")]
        [ReadOnly(isReadOnly: true)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime CreatedDate { get; set; }
        [DisplayName("權限")]
        [Required(ErrorMessage = "欄位必填")]
        public int AuthSN { get; set; }
        [DisplayName("使用中")]
        public bool Enabled { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin> Admin { get; set; }
        public virtual Auth Auth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Members> Members { get; set; }
    }
}
