//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_V3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupBuying
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupBuying()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public string ID { get; set; }
        public int StoreSN { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.DateTime Startdate { get; set; }
        public int CreatedPerson { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime RequireDate { get; set; }
        public System.DateTime CloseDate { get; set; }
        public string ShipAddress { get; set; }
        public int DeliverySN { get; set; }
        public Nullable<decimal> LimitMoney { get; set; }
        public Nullable<int> LimitNumber { get; set; }
        public bool Continued { get; set; }
        public int PaySN { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Members Members { get; set; }
        public virtual PayType PayType { get; set; }
        public virtual Stores Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
