//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_V3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manage
    {
        public int SN { get; set; }
        public int TypeSN { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DealDate { get; set; }
        public Nullable<int> AdminSN { get; set; }
        public int MemberSN { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Members Members { get; set; }
        public virtual ProblemType ProblemType { get; set; }
    }
}
